### ISSUE TITLE
Not all sidebar links are properly preserved

### ISSUE THREAD

**Issue by ashleytowner** [Nynir/WorldAnvil-to-MD#8]
Some sidebar links aren't preserved. 

Here's a screenshot of the sidebar in Worldanvil for a particular article of mine:
![image](https://github.com/Nynir/WorldAnvil-to-MD/assets/13824257/f80d26e0-1c99-4a0e-be3c-d9e9bd7b16cd)

Then here is the same sidebar info once it's been converted, viewed in obsidian:

![image](https://github.com/Nynir/WorldAnvil-to-MD/assets/13824257/7d50bdee-9755-490e-8dfd-089ade7314d4)

**Comment by ashleytowner** [comment]
It's worth noting that all of the things that weren't properly handled were links to other articles, not plain-text.

**Comment by Nynir** [comment]
Nice!
